# Generated by Django 5.1.4 on 2025-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Fjob',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Health Care'), (3, 'Civil Services'), (4, 'At Home'), (5, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Mjob',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Health Care'), (3, 'Civil Services'), (4, 'At Home'), (5, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Pstatus',
            field=models.IntegerField(choices=[(1, 'Living Together'), (2, 'Apart')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='famsize',
            field=models.IntegerField(choices=[(1, 'LE3'), (2, 'GT3')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='famsup',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.IntegerField(choices=[(1, 'Mother'), (2, 'Father'), (3, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='higher',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internet',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nursery',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Close to Home'), (2, 'Reputation'), (3, 'Course Preference'), (4, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='romantic',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolsup',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Dalc',
            field=models.IntegerField(choices=[(1, 'Very low'), (5, 'Very high')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fedu',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Primary'), (2, '5th to 9th'), (3, 'Secondary'), (4, 'Higher')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='G1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='G2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='G3',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Medu',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Primary'), (2, '5th to 9th'), (3, 'Secondary'), (4, 'Higher')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Walc',
            field=models.IntegerField(choices=[(1, 'Very low'), (5, 'Very high')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='absences',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='failures',
            field=models.IntegerField(choices=[(1, '1-2 failures'), (4, '3 or more failures')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='famrel',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='freetime',
            field=models.IntegerField(choices=[(1, 'Very low'), (5, 'Very high')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='goout',
            field=models.IntegerField(choices=[(1, 'Very low'), (5, 'Very high')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='health',
            field=models.IntegerField(choices=[(1, 'Very bad'), (5, 'Very good')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studytime',
            field=models.IntegerField(choices=[(1, '<2 hours'), (2, '2-5 hours'), (3, '5-10 hours'), (4, '>10 hours')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='traveltime',
            field=models.IntegerField(choices=[(1, '<15 min'), (2, '15-30 min'), (3, '30 min-1 hour'), (4, '>1 hour')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
